### ISSUE TITLE
拖拽视窗时将视窗全屏导致弹幕姬无响应，且无法操作屏幕

### ISSUE THREAD

**Issue by oscar172772** [xzso3/DanmakuPlugin_NewOnlineViewer#2]

**Comment by oscar172772** [comment]
請有空發給 copyliu@gmail.com 謝謝
2020/6/30 17:17:51
System.InvalidOperationException: Can only call DragMove when primary mouse button is down.
   at System.Windows.Window.DragMove()
   at DanmakuPlugin_NewOnlineViewer.ViewerWindow.Viewer_MouseDown(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)-------插件列表--------
题词版服务端	⑨	CopyLiu	copyliu@gmail.com	启用:True
新·在线人数视窗	1.0.1	Const	xzso3@outlook.com	启用:True
登录中心	1.2.3	宅急送队长	私信15253直播间主播或弹幕姬群内私聊	启用:True
Re: TTSCat	3.8.74.605	Elepover	elepover@outlook.com	启用:True
